name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'packages/react-icons/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/react-icons/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm --filter @menergia/react-icons type-check
